services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/home/eduard/Programming/currency-converter/data
    networks:
      - currency-converter-net

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - currency-converter-net
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8001:8000"
    networks:
      - currency-converter-net
    depends_on:
      - backend

networks:
  currency-converter-net:
    driver: bridge

volumes:
  postgres_data: